### ISSUE TITLE
Unhandled Exceptions Error

### ISSUE THREAD

**Issue by ramnath** [GGG-KILLER/CSS-And-Js-Minifier#1]
While running the program I got the following error:

```
************** Exception Text **************
System.UriFormatException: Invalid URI: The Uri string is too long.
   at System.UriHelper.EscapeString(String input, Int32 start, Int32 end, Char[] dest, Int32& destPos, Boolean isUriString, Char force1, Char force2, Char rsvd)
   at System.Uri.EscapeDataString(String stringToEscape)
   at System.Net.Http.FormUrlEncodedContent.Encode(String data)
   at System.Net.Http.FormUrlEncodedContent.GetContentByteArray(IEnumerable`1 nameValueCollection)
   at System.Net.Http.FormUrlEncodedContent..ctor(IEnumerable`1 nameValueCollection)
   at CSSAndJsMinifier.Form1.<MinifyCSS>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
```

However it did minify around 60% of the files.

Thanks.

**Comment by GGG-KILLER** [comment]
I think this is probably because of a too big file, I'll test it as soon as I have some free time.

Thank you for your report!

**Comment by GGG-KILLER** [comment]
Latest commit fixed this issue.
